import { StyleSheet } from 'react-native';
import { BELT_ITEM_WIDTH, DARK, PAPER, PAPER_LINE } from './constants';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#050112',
  },
  resetButton: {
    alignItems: 'center',
    backgroundColor: '#18122f',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 999,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    position: 'absolute',
    right: 16,
    top: 12,
    paddingHorizontal: 16,
    zIndex: 20,
  },
  resetButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontFamily: 'Cafe24PROSlim-Bold',
    lineHeight: 14,
  },
  bgImage: {
    ...StyleSheet.absoluteFill,
    alignSelf: 'center',
    height: '100%',
    width: '100%',
  },
  previewShell: {
    width: '100%',
  },
  phoneFrame: {
    backgroundColor: DARK,
    flex: 1,
  },
  safeAreaContent: {
    flex: 1,
  },
  screenPadding: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  authScreen: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  authPanel: {
    alignItems: 'stretch',
    alignSelf: 'center',
    gap: 12,
    marginTop: 136,
    width: '100%',
  },
  authTitle: {
    color: '#ffffff',
    fontFamily: 'Cafe24PROSlim-Bold',
    fontSize: 30,
    marginBottom: 6,
    textAlign: 'center',
  },
  authInput: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.18)',
    borderRadius: 6,
    borderWidth: 1,
    color: '#ffffff',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 16,
    includeFontPadding: true,
    lineHeight: 24,
    minHeight: 54,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  authSwitch: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  authSwitchText: {
    color: '#d4cfea',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 14,
  },
  apiMessage: {
    color: '#ffb8c0',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 14,
    textAlign: 'center',
  },
  topBackRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  backArrow: {
    color: '#ffffff',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 22,
    lineHeight: 22,
  },
  boxedIcon: {
    borderColor: '#ffffff',
    borderRadius: 3,
    borderWidth: 1,
    height: 14,
    width: 14,
  },
  topBackLabel: {
    color: '#ffffff',
    fontSize: 16,
    fontFamily: 'Cafe24PROSlim-Light',
  },
  landingHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  logoutButton: {
    alignItems: 'center',
    borderColor: 'rgba(255,255,255,0.46)',
    borderRadius: 999,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  logoutButtonText: {
    color: '#ffffff',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 13,
    lineHeight: 15,
  },
  landingTitleWrap: {
    alignItems: 'center',
    alignSelf: 'stretch',
    marginTop: 138,
  },
  landingTitle: {
    color: '#ffffff',
    fontSize: 50,
    fontFamily: 'Cafe24PROSlim-Bold',
    letterSpacing: 0,
    lineHeight: 56,
    textAlign: 'center',
    width: '100%',
  },
  centerBoxLarge: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  landingActions: {
    alignItems: 'center',
    gap: 12,
    marginBottom: 58,
  },
  landingPrimaryButton: {
    alignItems: 'center',
    backgroundColor: '#efe8f9',
    borderRadius: 999,
    height: 52,
    justifyContent: 'center',
    minWidth: 172,
    paddingHorizontal: 24,
  },
  landingPrimaryButtonText: {
    color: '#130c1f',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 20,
    lineHeight: 22,
  },
  landingSecondaryButton: {
    alignItems: 'center',
    borderColor: 'rgba(255,255,255,0.6)',
    borderRadius: 999,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    minWidth: 172,
    paddingHorizontal: 20,
  },
  landingSecondaryButtonText: {
    color: '#ffffff',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 15,
    lineHeight: 17,
  },
  actionPill: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#efe8f9',
    borderRadius: 999,
    height: 52,
    justifyContent: 'center',
    marginBottom: 68,
    paddingHorizontal: 24,
  },
  actionPillText: {
    color: '#130c1f',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 20,
    lineHeight: 22,
  },
  darkStage: {
    alignItems: 'center',
    backgroundColor: '#0a0523',
    flex: 1,
    overflow: 'hidden',
    paddingHorizontal: 20,
    paddingTop: 60,
  },
  tapeScreen: {
    alignItems: 'center',
    backgroundColor: '#0a0523',
    flex: 1,
    overflow: 'hidden',
  },
  stageTitleRow: {
    alignItems: 'center',
    alignSelf: 'stretch',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 20,
    zIndex: 2,
  },
  stageTitle: {
    color: '#f7f6fb',
    fontSize: 32,
    fontFamily: 'Cafe24PROSlim-Light',
    textAlign: 'center',
  },
  stageTitleStandalone: {
    alignSelf: 'stretch',
    marginTop: 20,
    zIndex: 2,
  },
  stageAccent: {
    color: '#db4451',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 28,
    textAlign: 'center',
  },
  helperText: {
    alignSelf: 'stretch',
    color: '#a8a3b8',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 14,
    marginTop: 10,
    textAlign: 'center',
    zIndex: 2,
  },
  stageError: {
    alignSelf: 'center',
    bottom: 42,
    color: '#ffb8c0',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 14,
    left: 20,
    position: 'absolute',
    right: 20,
    textAlign: 'center',
    zIndex: 5,
  },
  stageBoxWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 38,
    width: '100%',
    zIndex: 2,
  },
  stageBottomElement: {
    marginTop: -8,
    zIndex: 2,
  },
  tapeWebViewWrap: {
    height: 590,
    left: 0,
    overflow: 'hidden',
    position: 'absolute',
    right: 0,
    top: 82,
    width: '100%',
    zIndex: 2,
  },
  tapeWebView: {
    backgroundColor: 'transparent',
    height: '100%',
    width: '100%',
  },
  tapeCompleteButton: {
    alignItems: 'center',
    bottom: 108,
    height: 48,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    zIndex: 3,
  },
  tapeCompleteText: {
    color: '#ffffff',
    fontFamily: 'Cafe24PROSlim-Light',
    fontSize: 24,
    lineHeight: 26,
    textAlign: 'center',
  },
  actionGhost: {
    alignItems: 'center',
    borderColor: '#ffffff',
    borderRadius: 10,
    borderWidth: 1,
    height: 52,
    justifyContent: 'center',
    marginTop: 42,
    paddingHorizontal: 28,
    zIndex: 2,
  },
  actionGhostDisabled: {
    opacity: 0.35,
  },
  actionGhostText: {
    color: '#ffffff',
    fontSize: 24,
    fontFamily: 'Cafe24PROSlim-Light',
    lineHeight: 26,
  },
  loadingText: {
    alignSelf: 'stretch',
    color: '#e8e5f0',
    fontSize: 24,
    fontFamily: 'Cafe24PROSlim-Light',
    marginTop: 140,
    textAlign: 'center',
    zIndex: 2,
  },
  letterScreen: {
    flex: 1,
    position: 'relative',
  },
  letterDarkTop: {
    flexShrink: 0,
    height: 340,
    overflow: 'hidden',
  },
  letterBoxWrap: {
    alignItems: 'center',
    bottom: 12,
    position: 'absolute',
    width: '100%',
    zIndex: 2,
  },
  paperCard: {
    backgroundColor: PAPER,
    flex: 1,
    paddingBottom: 26,
    paddingHorizontal: 32,
    paddingTop: 34,
  },
  paperTo: {
    color: '#171717',
    fontSize: 28,
    fontFamily: 'Cafe24PROSlim-Bold',
    marginBottom: 32,
  },
  ruledTextArea: {
    flex: 1,
    position: 'relative',
  },
  ruledLines: {
    bottom: 0,
    gap: 30,
    justifyContent: 'flex-start',
    left: 0,
    paddingTop: 28,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  composeInput: {
    color: '#2b2b2b',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 18,
    lineHeight: 30,
    minHeight: 210,
    paddingTop: 0,
    textAlignVertical: 'top',
    zIndex: 1,
  },
  paperLineStack: {
    gap: 26,
    marginTop: -8,
  },
  paperLines: {
    gap: 16,
  },
  paperLineRow: {
    gap: 8,
  },
  paperBody: {
    color: '#2b2b2b',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 18,
    minHeight: 24,
  },
  paperReadBody: {
    color: '#2b2b2b',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 18,
    lineHeight: 30,
    minHeight: 210,
    textAlignVertical: 'top',
    zIndex: 1,
  },
  paperRule: {
    backgroundColor: PAPER_LINE,
    height: 2,
    opacity: 0.9,
    width: '100%',
  },
  paperCta: {
    color: '#9f9b93',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 19,
    marginTop: 74,
    textAlign: 'center',
  },
  paperActionOverlay: {
    bottom: 28,
    left: 0,
    position: 'absolute',
    right: 0,
    zIndex: 4,
  },
  paperActionRow: {
    alignItems: 'center',
    marginTop: 28,
  },
  paperError: {
    color: '#a2353f',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 14,
    marginTop: 10,
    textAlign: 'center',
  },
  lockerShell: {
    backgroundColor: 'transparent',
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 22,
  },
  lockerLead: {
    color: '#f6f3fa',
    fontSize: 24,
    fontFamily: 'Cafe24PROSlim-Light',
    marginTop: 64,
    textAlign: 'center',
  },
  lockerStateText: {
    color: '#d4cfea',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 16,
    marginTop: 58,
    textAlign: 'center',
  },
  lockerError: {
    color: '#ffb8c0',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 14,
    marginTop: 16,
    textAlign: 'center',
  },
  gridRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 28,
  },
  packageTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 16,
    borderWidth: 1,
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 20,
    width: '47%',
  },
  conveyorArea: {
    height: 460,
    marginTop: 36,
    overflow: 'hidden',
    width: '100%',
  },
  conveyorItem: {
    alignItems: 'center',
    left: 0,
    position: 'absolute',
    top: 0,
    width: BELT_ITEM_WIDTH,
  },
  packageFrom: {
    color: '#d4cfea',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 13,
    textAlign: 'center',
  },
  conveyorPackageFrom: {
    color: '#d4cfea',
    fontFamily: 'Cafe24PROSlim-Bold',
    fontSize: 18,
    marginTop: 20,
    textAlign: 'center',
  },
  packageTagline: {
    color: '#f6f3fa',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 18,
    marginTop: 12,
    textAlign: 'center',
  },
  emptyLockerState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyLockerText: {
    color: '#a8a3b8',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 16,
    marginTop: 18,
    textAlign: 'center',
  },
  replyLockerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 34,
  },
  replyLockerTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(11,8,31,0.78)',
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 228,
    paddingHorizontal: 10,
    paddingTop: 16,
    width: '48%',
  },
  replyLockerFrom: {
    color: '#f6f3fa',
    fontFamily: 'Cafe24PROSlim-Bold',
    fontSize: 14,
    lineHeight: 17,
    marginTop: 12,
    textAlign: 'center',
  },
  replyLockerTo: {
    color: '#bdb7d0',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 13,
    lineHeight: 16,
    marginTop: 5,
    textAlign: 'center',
  },
  replyLabelDetailWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 58,
    paddingHorizontal: 4,
    width: '100%',
  },
  detailBoxWrap: {
    alignItems: 'center',
    height: 320,
    justifyContent: 'center',
    marginTop: 40,
  },
  lockerDetailAction: {
    marginTop: 28,
  },
  replyEditor: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 22,
    borderWidth: 1,
    marginTop: 12,
    padding: 16,
    width: '100%',
    zIndex: 2,
  },
  replyLabel: {
    color: '#e7e2f0',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 14,
    marginBottom: 10,
  },
  replyInput: {
    color: '#ffffff',
    fontFamily: 'Cafe24PROSlim-Regular',
    fontSize: 16,
    lineHeight: 24,
    minHeight: 120,
    textAlignVertical: 'top',
  },
  attachStage: {
    alignItems: 'center',
    backgroundColor: '#0a0523',
    flex: 1,
    overflow: 'hidden',
    paddingHorizontal: 18,
    paddingTop: 80,
  },
  attachTitle: {
    alignSelf: 'stretch',
    color: '#f7f6fb',
    fontFamily: 'Cafe24PROSlim-Light',
    fontSize: 31,
    lineHeight: 36,
    textAlign: 'center',
    zIndex: 2,
  },
  attachScene: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    maxHeight: 500,
    minHeight: 390,
    width: '100%',
    zIndex: 2,
  },
  attachBoxWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -44,
  },
  attachLabelCard: {
    backgroundColor: PAPER,
    borderColor: '#171717',
    borderWidth: 3,
    bottom: 18,
    maxWidth: 330,
    padding: 7,
    position: 'absolute',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.26,
    shadowRadius: 18,
    transform: [{ rotate: '-2deg' }],
    width: '92%',
  },
  attachLabelHeader: {
    alignItems: 'center',
    borderColor: '#111111',
    borderWidth: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  attachLabelTitle: {
    color: '#111111',
    fontFamily: 'Cafe24PROSlim-Bold',
    fontSize: 25,
    lineHeight: 29,
  },
  attachLabelInfo: {
    borderColor: '#234db1',
    borderWidth: 2,
    gap: 4,
    marginTop: 4,
    minHeight: 52,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  attachLabelSmall: {
    color: '#111111',
    fontFamily: 'Cafe24PROSlim-Bold',
    fontSize: 13,
    lineHeight: 15,
  },
  attachMemoBox: {
    borderColor: '#cf1d1d',
    borderWidth: 2,
    flexDirection: 'row',
    marginTop: 4,
    minHeight: 122,
  },
  attachMemoTag: {
    alignItems: 'center',
    borderColor: '#cf1d1d',
    borderRightWidth: 2,
    justifyContent: 'center',
    width: 28,
  },
  attachMemoTagText: {
    color: '#111111',
    fontFamily: 'Cafe24PROSlim-Bold',
    fontSize: 14,
    lineHeight: 16,
    textAlign: 'center',
  },
  attachReplyInput: {
    color: '#111111',
    flex: 1,
    fontFamily: 'Cafe24PROSlim-Bold',
    fontSize: 15,
    lineHeight: 21,
    minHeight: 118,
    paddingHorizontal: 11,
    paddingVertical: 10,
    textAlignVertical: 'top',
  },
  parcelTopWrap: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#e7b25c',
    borderRadius: 14,
    height: 172,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 248,
  },
  parcelLid: {
    backgroundColor: '#f6cd83',
    height: 44,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  parcelSeam: {
    backgroundColor: 'rgba(122,86,28,0.35)',
    height: 2,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 44,
  },
  parcelSticker: {
    alignItems: 'center',
    backgroundColor: '#f7f3e8',
    borderColor: '#5a4a28',
    borderRadius: 4,
    borderWidth: 1,
    gap: 8,
    height: 88,
    justifyContent: 'center',
    marginTop: 22,
    paddingHorizontal: 14,
    width: 150,
  },
  parcelStickerLine: {
    backgroundColor: '#3a3a3a',
    height: 4,
    width: '100%',
  },
  parcelStickerLineShort: {
    width: '55%',
  },
  shippingCard: {
    backgroundColor: PAPER,
    borderColor: '#222222',
    borderWidth: 4,
    maxWidth: 358,
    padding: 8,
    width: '100%',
  },
  shippingCardCompact: {
    maxWidth: 356,
  },
  shippingHeader: {
    alignItems: 'center',
    borderColor: '#111111',
    borderWidth: 3,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  shippingCode: {
    color: '#111111',
    fontSize: 28,
    fontFamily: 'Cafe24PROSlim-Bold',
  },
  shippingInfo: {
    borderColor: '#234db1',
    borderWidth: 3,
    flexDirection: 'row',
    marginTop: 4,
    minHeight: 64,
  },
  shippingColTitle: {
    alignItems: 'center',
    borderColor: '#111111',
    borderRightWidth: 3,
    justifyContent: 'center',
    width: 28,
  },
  shippingColBody: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  shippingText: {
    color: '#111111',
    fontSize: 14,
    fontFamily: 'Cafe24PROSlim-Bold',
  },
  shippingMemo: {
    borderColor: '#cf1d1d',
    borderWidth: 3,
    flexDirection: 'row',
    marginTop: 4,
    minHeight: 108,
  },
  shippingColTitleRed: {
    alignItems: 'center',
    borderColor: '#cf1d1d',
    borderRightWidth: 3,
    justifyContent: 'center',
    width: 28,
  },
  shippingMemoText: {
    color: '#111111',
    flex: 1,
    fontSize: 15,
    fontFamily: 'Cafe24PROSlim-Bold',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  verticalKorean: {
    color: '#111111',
    fontSize: 14,
    fontFamily: 'Cafe24PROSlim-Bold',
    lineHeight: 16,
    textAlign: 'center',
  },
  verticalKoreanRed: {
    color: '#111111',
    fontSize: 14,
    fontFamily: 'Cafe24PROSlim-Bold',
    lineHeight: 16,
    textAlign: 'center',
  },
  barcode: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 2,
    height: 34,
  },
  barcodeSmall: {
    marginHorizontal: 8,
  },
  barcodeLine: {
    backgroundColor: '#111111',
    height: '100%',
  },
  barcodeThick: {
    width: 3,
  },
  barcodeThin: {
    width: 1,
  },
  stampOverlay: {
    bottom: 0,
    position: 'absolute',
    right: -20,
  },
});
